### ISSUE TITLE
Create a custom state 

### ISSUE THREAD

**Issue by maxwellflitton** [OasisLMF/camel#14]
Right now Camel manages its state by pointing to an ```S3``` bucket. Whilst this is a good first step as it avoids multiple people accidentally running multiple instances of the same model resulting in dangling systems and servers. 

However, there is a desire to support multiple states where we can have different users running different instances of a model. Right now we have a [basecamp](https://github.com/OasisLMF/camel/tree/main/camel/basecamp) module that tracks the interactions of different users to a project. In the [basecamp](https://github.com/OasisLMF/camel/tree/main/camel/basecamp) we should use the [project adapter](https://github.com/OasisLMF/camel/blob/main/camel/basecamp/projects/adapters/terra_apply.py) to handle the ```s3``` state for each project as we can have multiple projects for a single model run.

**Comment by benhayes21** [comment]
is this still relevant or can we close it?

**Comment by maxwellflitton** [comment]
@benhayes21 the custom state should work now as I've tested it however, it has to be merged with the following pull request:
https://github.com/OasisLMF/camel/pull/39/files

**Comment by maxwellflitton** [comment]
This has now been merged and custom state is working
